### ISSUE TITLE
Bug while installing from source on macos

### ISSUE THREAD

**Issue by abhijith96** [coin-or/CoinUtils#181] opened 2021-06-09 06:28 UTC
My macos version is 10.15.6. the compiler i used is apple clang 11.0 cppstd was set to c++11.
i was getting these warnings while doing make.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libCoinUtils.a(CoinAlloc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libCoinUtils.a(CoinPresolvePsdebug.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libCoinUtils.a(CoinWarmStartVector.o) has no symbols
ranlib .libs/libCoinUtils.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libCoinUtils.a(CoinAlloc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libCoinUtils.a(CoinPresolvePsdebug.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libCoinUtils.a(CoinWarmStartVector.o) has no symbols

and while reinstalling the package i was getting error while running make install.
the error was install recursive Headers failed. and only one header file was copied before make install stoped abrubtly.

**Comment by abhijith96** [comment] 2021-06-09 06:35
make[3]: *** [install-includecoinHEADERS] Error 1 this was the error i got while reinstalling.

**Comment by tkralphs** [comment] 2021-06-11 20:20
We'll need more information to have an idea where the problem could be coming from. It appears you are not using any of the recommended ways of building, but I'm not sure. The easiest ways would be homebrew, conda, or coinbrew, as documented (see the README). If you can specify how you got the code, exactly what build commands you're using, etc., we can try to help. You might also check out the recent CI builds, some of which are on OS X with clang.

**Comment by abhijith96** [comment] 2021-06-14 05:10
https://github.com/coin-or/CoinUtils/archive/releases/2.11.4.tar.gz ,
I am getting the source code from this url. Then i extracted the tar file. 
and tried to install using the Makefile. I ran these commands.
./configure -C
make
make install

configure and make part ran successfully.
But "make install" command failed with make[3]: *** [install-includecoinHEADERS]  this error.
In the installation directory's include folder. Only this one header file " Coin_C_defines.h" was generated by "make install" command before terminating.

**Comment by tkralphs** [comment] 2021-06-16 17:03
I need more of the output to know what the failure is. Please attach the full output. You might also check the existing issues.

**Comment by SpaceIm** [comment] 2021-08-28 18:53
@tkralphs It's an error we see randomly on macOS in conan recipe of coin-utils 2.11.4 https://github.com/conan-io/conan-center-index/issues/5820 (but also others coin libraries I think):

Here is install log when I cross-compile to iOS armv8. It usually fails half the time.

```
Making install in CoinUtils
Making install in src
/Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/build/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/source_subfolder/CoinUtils/install-sh -c -m 644 config_coinutils.h /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/include/coin/CoinUtilsConfig.h
test -z "/Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/lib" || /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/build/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/source_subfolder/CoinUtils/install-sh -d "/Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/lib"
test -z "/Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/include/coin" || /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/build/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/source_subfolder/CoinUtils/install-sh -d "/Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/include/coin"
mkdir: /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/include: File exists
mkdir: /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/include/coin: File exists
make[3]: *** [install-includecoinHEADERS] Error 1
make[3]: *** Waiting for unfinished jobs....
 /bin/sh ../../libtool --mode=install /usr/bin/install -c  'libCoinUtils.la' '/Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/lib/libCoinUtils.la'
/usr/bin/install -c .libs/libCoinUtils.lai /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/lib/libCoinUtils.la
/usr/bin/install -c .libs/libCoinUtils.a /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/lib/libCoinUtils.a
chmod 644 /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/lib/libCoinUtils.a
ranlib /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/lib/libCoinUtils.a
----------------------------------------------------------------------
Libraries have been installed in:
   /Users/spaceim/.conan/data/coin-utils/2.11.4/_/_/package/23de7d0b6b9ba33f9fbcfda089d6bda191ba7775/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Comment by SpaceIm** [comment] 2021-08-28 19:05
Seems to be a parallelization issue. When I call `make install -j1` instead of `make install -j12`, it always works.

**Comment by tkralphs** [comment] 2021-08-29 02:48
Ah, yes, there is an issue with parallelization that only occurs on MacOS. We've also de-parallelized our homebrew recipes for a similar reason. Somewhere, there's another issue open on this, but I can't find it. I've tried to track down the reason, but it may be fixed once I push the current master out to release, since this has an upgrade to the build system to use current autotools.

**Comment by yingopq** [comment] 2022-10-12 02:10
> Ah, yes, there is an issue with parallelization that only occurs on MacOS. We've also de-parallelized our homebrew recipes for a similar reason. **Somewhere, there's another issue open on this, but I can't find it. I've tried to track down the reason, but it may be fixed once I push the current master out to release, since this has an upgrade to the build system to use current autotools.**

Hi @tkralphs,
Did you mean there had an issue when using current autotool to package the code of the master branch to release?
Because now i have a problem when compile packgae Clp & it would report an error “_ClpMatrixBase.hpp:9:10: fatal error: CoinTypes.h: No such file or directory”_. Then i cheked the locally downloaded code of CoinUtils, found that the file name is  CoinTypes.hpp.
We download the 2.11.6 source tar code from release page not by using coinbrew to fetch from github.com/coin-or/CoinUtils. If we use coinbrew, it did not report thar error.
And i cheked the master branch code, found the file name still were CoinTypes.hpp in several files, namely [MSVisualStudio/v9alt/libCoinUtils.vcproj](https://github.com/coin-or/CoinUtils/blob/ab8cedf4cf4a163725251666f87276e44f492e81/MSVisualStudio/v9alt/libCoinUtils.vcproj)
[MSVisualStudio/v10alt/libCoinUtils.vcxproj](https://github.com/coin-or/CoinUtils/blob/ab8cedf4cf4a163725251666f87276e44f492e81/MSVisualStudio/v10alt/libCoinUtils.vcxproj)
[MSVisualStudio/v9/libCoinUtils/libCoinUtils.vcproj](https://github.com/coin-or/CoinUtils/blob/ab8cedf4cf4a163725251666f87276e44f492e81/MSVisualStudio/v9/libCoinUtils/libCoinUtils.vcproj)
[MSVisualStudio/v14/libCoinUtils/libCoinUtils.vcxproj](https://github.com/coin-or/CoinUtils/blob/ab8cedf4cf4a163725251666f87276e44f492e81/MSVisualStudio/v14/libCoinUtils/libCoinUtils.vcxproj)
[MSVisualStudio/v10/libCoinUtils/libCoinUtils.vcxproj](https://github.com/coin-or/CoinUtils/blob/ab8cedf4cf4a163725251666f87276e44f492e81/MSVisualStudio/v10/libCoinUtils/libCoinUtils.vcxproj)
I'm not sure if this is related to the problem & i am glad to see your reply. 
Thanks!

**Comment by tkralphs** [comment] 2022-10-12 02:22
I doubt the issue is related to this issue, which I guess should be closed. You seem to be mixing incompatible versions of packages. The reason `coinbrew` works is because it automatically grabs the right dependencies. I guess you are mixing the `master` branch of Clp with a release branch of CoinUtils, but these are not compatible. Check `.coin-or/config.yml` for the right dependencies (or just use `coinbrew`).

**Comment by yingopq** [comment] 2022-10-12 02:45
Glad to your reply so fast!
Yes, I got you mean the Clp master branch is compatible wirh CoinUtils master branch.
OK, I would use the master branch CoinUtils code before you solve the problem that release code is not same with master branch.
Thanks very much.

**Closed as completed** 2023-04-10 14:35 UTC
